### ISSUE TITLE
Mining drill mode 4 not optimal for digging following change 5cf765b2

### ISSUE THREAD

**Issue by Talinf** [minetest-technic/technic#122]
A change was made to mining drill mode 4. The comment says: 3 tall, selected in the middle but the last change remove the selected node and the 2 under. If you want the same action as before, you have to point at the top node which have the side effect of not being able to see forward and so risk to be immersed in lava ...

**Comment by t4im** [comment]
@ShadowNinja a digging down function was allready being fullfilled by the 3-forward mode, if you faced down…

I consider the current functionality a lot more unintuitive, as one would expect the 3-tall and 3-wide functions to behave similar, not arbitrarily different.

I second a revert of the change.
Especially since the commit of 5cf765b2 states "Localize most variables", so any chance in behavior must have obviously been a mistake anyway.

**Comment by VanessaE** [comment]
No response from the author in forever.  Closing...
