### ISSUE TITLE
Mining laser's path doesn't match the aim point

### ISSUE THREAD

**Issue by fmoody** [minetest-technic/technic#163]
I haven't tracked down when the change occurred but the current mining laser path of travel appears to originate from lower than the aim point and so the aim is off.

**Comment by JDCodeIt** [comment]
I made a change to mining_lasers.lua that may be interesting to include. It basically translates a sphere of destruction along the path the player is looking and digs all within the 1 meter radius. This removes the rayIter function. Someone may have a better idea of what node groups to target.

replaced in function laser_shoot:
...
  for pos in rayIter(start_pos, dir, range) do
    if minetest.is_protected(pos, player_name) then
      minetest.record_protection_violation(pos, player_name)
      break
    end
    local node = minetest.get_node_or_nil(pos)
    if not node then
      break
    end
    if not no_destroy[node.name] then
      laser_node(pos, node, player)
    end
  end
...

With this:
	for iRange = 1, range do
	  local node = nil
	  local vPos = vector.add(start_pos, vector.multiply(dir, iRange))
	  for jSphere = 1, 27 do
      local pos = minetest.find_node_near(vPos, 1, {"group:crumbly", "group:cracky", "group:snappy", "group:choppy", "group:oddly_breakable_by_hand"})
      if(pos) then
        node =  minetest.get_node_or_nil(pos)
        if not node then
           break
        end
      else
        break
      end   
      if not no_destroy[node.name] then
        laser_node(pos, node, player)
      end
    end
end

**Comment by ShadowNinja** [comment]
@JDCodeIt: That should be a separate issue, but I don't like it because:
  * Instead of mathematically finding every node that the ray would hit it simply steps down the ray checking for anything in range and destroying it.  This means that it can miss nodes that it should have destroyed *and* that it spends extra CPU time checking nodes that it's already destroyed.
  * Code style!
  * It uses a 27-iteration for loop instead of just an infinite loop with a break when there's nothing left (`while pos`).
  * It only checks nodes in a few groups.
  * It's a lot less efficient.

**Comment by JDCodeIt** [comment]
You should try it. I put it on my server, and had no issue with lag.
- The current code doesn't act like a laser in the direction the user points
- Substance and sequence of code is there, and of course one can adjust the style
- I purposefully avoid the possibility of infinite loops, where in this case 27 is the maximum that could be found (3 cubed)
- Is there another minetest function that can get all nodes in a radius?  I tried passing an empty table, but it finds nothing then.
- I found the minetest.find_node_near() very efficient. Notice the break statement on the first time the minetest function returns nil.  No need to process all 27 nodes each time.

**Comment by asl97** [comment]
@JDCodeIt where is the check for protection?

you could also use minetest.find_nodes_in_area instead of that loop

@ShadowNinja it look like it is currently digging one node below and one node to the right of the pointed node in a L shape, just enter the ground using noclip and shoot.

eg(this is using +2.5, it seem to correct the y pos): note the z pos
````lua
{	y = 23.5,	x = -135.25999450684,	z = -6.8330001831055} -- player pos
{	y = 26,	x = -135.25999450684,	z = -6.8330001831055} -- start pos
{	y = 26,	x = -135,	z = -8} -- first dig node
````

seem like an rounding error, i would expect it to be -7 instead of -8.

**Comment by asl97** [comment]
figure out the angle problem, it due to #159 and maybe #100
i agree that it's good that it doesn't leave unconnected air holes,  but i prefer the wider path

**Comment by HybridDog** [comment]
maybe you could temporary use this function http://dev.minetest.net/User:Hybrid_Dog#vector_extras until the problem is fixed

**Comment by asl97** [comment]
@HybridDog i am already using vertor_extras
____
it used to be just point and click and it would hit all the nodes in the path.

but now, the start pos is off and shooting diagonal doesn't remove the most possible number of node, it end up not removing the pointed node and make it hard to predict what it would hit.

it become fairly impossible to use laser for precision digging, i used to be able to use it for farming, digging path, even shooting apples in trees without hitting the leaves just for fun because i know what it would hit.

in the past when i was playing, people keep thinking that laser just make ugly holes and impossible to use it for anything but destruction and i prove them wrong plenty of time

**Comment by JDCodeIt** [comment]
asl97, good point on protection, but I call the already developed local 
laser_node() function, which probably should handle this. It calls 
remove_node() for non-liquid registered nodes, and then node_dig() for 
all nodes.

Since protection has become more standard, seems all modders would need 
to include some special code there.  The MineTest API maintainers might 
want to consider building this deeper into the system if it is not there 
already, so the remove_node() would do something about this internally, 
or maybe provide an optimized function remove_node_protected().

**Comment by asl97** [comment]
@JDCodeIt laser_node no longer check for the protection and it's a fairly good thing too, i don't know if node_dig or remove_node check it but mods like the laser should check for the protection itself cause shooting a mk3 in a protected area could easily get one banned simply because of the number of time `minetest.record_protection_violation` is called (if remove_node or node_dig call it)

this is currently not a problem because the laser stop as soon as it hit a single protected node while your code doesn't.

also, you should open the issue in the browser cause github doesn't send a email when a comment/post get updated.

**Comment by HybridDog** [comment]
>it end up not removing the pointed node and make it hard to predict what it would hit.

maybe somewhere pairs instead of ipairs is used

**Comment by JDCodeIt** [comment]
Certainly we could include the protection check, then bail out of the function from the inner most loop on the first hit of a protected node: 
```lua
...
      local pos = minetest.find_node_near(vPos, 1, {"group:crumbly", "group:cracky",
          "group:snappy", "group:choppy", "group:oddly_breakable_by_hand", "group:dig_immediate"})
      if(pos) then
        if minetest.is_protected(pos, player_name) then
          minetest.record_protection_violation(pos, player_name)
          return
        end
        node =  minetest.get_node_or_nil(pos)
        if not node then
           break
        end
...
```

**Comment by HybridDog** [comment]
l just noticed that somwhow there's no particle…

**Comment by asl97** [comment]
estimated shot path in green,
estimated pointed node in blue,
expected dug node but isn't dug in red:
![test](https://cloud.githubusercontent.com/assets/4752645/9005483/1b2c8aae-37b1-11e5-9dd1-47c121c9c725.png)
