### ISSUE TITLE
Infinity source of sand

### ISSUE THREAD

**Issue by 163140** [minetest-technic/technic#171]
Compressor make a sandstone from one sand. Each sandstone can be converted into 4 sand. Solution: redefine sandstone->sand recipe 1 sandstone -> 1 sand/

**Comment by thatgraemeguy** [comment]
There is no compressor recipe that makes sandstone from sand.

**Comment by 163140** [comment]
I'm sorry, i was wrong

**Comment by asl97** [comment]
just for completeness:
the recipe was remove on [Jul 3, 2014](https://github.com/minetest-technic/technic/commit/c0a17396bf093360f266a693c860cfad0b7ebbfe)(1)
re-added on [Jan 19, 2015](https://github.com/minetest-technic/technic/commit/9d3f7304fb1bde462a82a7f338c1d5064a396f41)
tweaked on [Jan 30, 2015](https://github.com/minetest-technic/technic/commit/a8c097bcd914b5722a7a211e0382bf82c96d32f8)

(1): long before this issue was make, however some server run older version of technic that was affected by this bug, so @163140 isn't completely wrong.
