### ISSUE TITLE
Quarry prone to crashing.

### ISSUE THREAD

**Issue by kaeza** [minetest-technic/technic#172]
The quarry calls the node's `on_dig` callback passing `nil` as `player`.

This confuses mods which expect `player` to never be `nil`, like `doors` and `signs_lib`.

The MT Lua API does not mention in the documentation for any of the relevant functions that the player can be a nil value, so it is a bug on the part of the technic mod.

To reproduce:
* Put a door or a sign from [signs_lib](https://github.com/VanessaE/homedecor_modpack). I'm sure there are tons of other nodes out there for which this bug also manifests.
* Put a quarry next to it.
* Power up the quarry to dig the node placed in step 1.

Stack traceback: https://gist.github.com/kaeza/c629bd768b09f4edfca7

It was discussed on the IRC channel, and the best approach would be to implement it using "fake player refs".

Leaving this here so it does not get lost.

**Comment by ShadowNinja** [comment]
The code originally used `dig_node`, which has some extra checks and calls callbacks.  It should be changed back.

It also uses a whole bunch of completely uncommented math now that's hard to understand.

**Comment by t4im** [comment]
In fact switching back to `dig_node` will _continue_ calling the can_dig with a nil player.
So that is currently official behavior.

As mentioned in irc, this is formost an issue to be solved in minetest first.
Either the documentation is missing this information about nil-players being allowed to be passed
or alternativly minetest requires a change of `dig_node`

Then again with minetest/minetest#2015 dig_node might need a small behavioral overhaul anyway.

**Comment by VanessaE** [comment]
I haven't seen quarries crash in quite a long time, let alone from anything referenced here.

**Comment by t4im** [comment]
And there's [smoketest](https://github.com/t4im/shakedown#smoketest) now to find exactly this kind of issues (test for this particular case included) :)
