### ISSUE TITLE
Fix coding style

### ISSUE THREAD

**Issue by ShadowNinja** [minetest-technic/technic#49]
http://dev.minetest.net/Lua_code_style_guidelines

**Comment by yo-we** [comment]
The  tab vs space  discussion is as old as the tab itself. The point missing from the discussion above is the portability problem, the (logically superior) use of tabulations inherently has: it depends on context (i.e. the local interpretation, how many virtual spaces to introduce for a given tabulation character). 
 This context can be different for code from different sources (one person using 8-space-wide-tabulations, another one 2-space-wide-tabulation)  AND  the "logical" approach of tabulation makes it opposed to the always-same-width character of spaces. The logical consequence is that: Tabulations can only be used correctly on project level if *all* contributors with no exception use always the same width for tabulations.
 Because this point can not be guaranteed, the consequence for coding guidelines is in my eyes simply to interdict tabulations because they need further rules and settings to work correctly.
 On the other hand, using pure space and no tabulations, the presentation is always stable and the same.
 The reduction of the size of a file using tabs is not a technically valuable argument anymore, these days. And I did not see anybody do code review on paper with numbered columns within the past 20 years (where having the code aligned to the columns already present on the paper is a gain).
  
There is no technical need for tabulations.
Tabulations add complexity.
There is no notable gain using tabulations vs spaces.
Spaces can not be entirely replaced by tabulations in a serious approach.
No need, no gain, there is no technical *justification* for the the use of tabulations.
==> As a consequence: Get entirely rid of tabulations.

If you do not want to do this clean but somehow radical thing, please fix at least the related logical problem in the coding guidelines: Having alignment with spaces and tabulations mixed, you *must* define and enforce the width of the tabulation.

**Comment by HybridDog** [comment]
>Having alignment with spaces and tabulations mixed, you must define and enforce the width of the tabulation.

No, lua is simple, you can easily automatically detect the tab size l think.

**Comment by hdastwb** [comment]
@yo-we, I think @ShadowNinja put it well a couple of comments up:
> Tabs are to be used only for indenting blocks of code. If you want to align something to make it look neater you should use spaces.
> The fact that you can change the width of tabs is a feature, hdastwb can use two space width while I use eight space width.

Using tabs for *alignment* is problematic; however, using tabs purely for *indentation* is acceptable because the width of indents doesn't matter as long as they are consistent in a given file. The fact that contributers can set different tab widths is an advantage when tabs are used correctly (for indentation only) because contributers can then modify the indentation width as they edit to suit their personal preferences without changing how the code looks for anyone else.

**Comment by yo-we** [comment]
@hdastwb: What you wrote and what you cited does not address the point I described: That point is purely mathematical and not linked to habits, existing rules or editors.
The exact point where the mix of tabulations and spaces for code formatting is messed up by changing the tabulation width is:
 * On alignment (by use of white-space) of elements of different lines, which have been indented by different numbers of preceding tabulation characters.

I know that the formulation is a bit abstract, if you want to see an example, I will provide it.

PS: What is so funny about this exchange: Nobody cites the *need*, or *specification*, to derive the solution from :)

**Comment by ShadowNinja** [comment]
@yo-we: We don't mix tabs and spaces for indentation, we use only tabs.  Likewise, we don't mix tabs and spaces for alignment, we use only spaces.  These are two very distinct roles.  Here's an example of some properly indented and aligned code that will look good with any tab width (`->` = tab, dot is space):
```Lua
if.foo.then
->      local.some_str.......=."Some.string"
->      local.some_other_str.=."Another.string"
end
```

It seems that you're arguing the this won't work:
```Lua
local...a.=.false
if.foo.then
->      a.=.true
end
```
However, this is *very bad style*, since you're grouping things together (by alignment) that are in different logical units of the program.

As for specification, there is http://dev.minetest.net/Lua_code_style_guidelines.

**Comment by ShadowNinja** [comment]
Closing as code style is mostly conformant now.
